collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4336918
color:
  saturation: 0.9721807
  brandStrength: 0.3870968
  lightness: 0.6244702
  brandColors:
    - '#FFFFFF'
    - '#EE534F'
    - '#525252'
    - '#000000'
    - '#898989'
  rhythmicContrast: 0.9579778
layout_spectrum: 0.3010753
name: Dailysmart
